[package]
name = "dungeon-crawler"
version = "0.2.0"
authors = ["Jaak Randmets <jaak.ra@gmail.com>"]
edition = "2018"

[dependencies]
static_assertions = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
log = "0.4"
env_logger = "0.6"
curl = "0.4"
lazy_static = "1.3"
regex = "1.2"
csv = "1.1"
dotenv = "0.14"
chrono = "0.4"
crossbeam = "0.7"
crossbeam-channel = "0.3"
structopt = "0.2"
tempfile = "3.0"
cuckoofilter = "0.3"
fs2 = "0.4"